### ISSUE TITLE
[feat] 쪽지 페이지 API 연동

### ISSUE THREAD

**Issue by sangminlee98** [Team13-MoaMoa/frontend#28]
## ✨ 만들고자 하는 기능
쪽지 페이지 API 연동하기

## ✔️ 해당 기능을 구현하기 위해 할 일
- [ ] Axios 설정하기
- [ ] API 명세서 확인하여 타입 설정하기

## 🗓️ 예상기간
7월4일 ~ 7월9일

**Comment by wisdomyeon** [comment]
g
